Update patch set 9
Patch Set 9:

Oh sorry, I botched the git review and was still on master.  Here goes.  Not a happy result.

--


clott@ubuntu18-cl778h:~/git/xapp-frame-py$ tox -e code
GLOB sdist-make: /home/clott/git/xapp-frame-py/setup.py
code inst-nodeps: /home/clott/git/xapp-frame-py/.tox/dist/ricxappframe-0.7.0.zip
code installed: attrs==19.3.0,coverage==5.0.4,hiredis==1.0.1,mdclogpy==1.1.1,more-itertools==8.2.0,msgpack==1.0.0,packaging==20.3,pkg-resources==0.0.0,pluggy==0.13.1,py==1.8.1,pyparsing==2.4.6,pytest==5.4.1,pytest-cov==2.8.1,redis==3.4.1,ricsdl==2.0.3,ricxappframe==0.7.0,rmr==4.0.0,six==1.14.0,wcwidth==0.1.9
code runtests: PYTHONHASHSEED='921507989'
code runtests: commands[0] | pytest --cov ricxappframe --cov-report xml --cov-report term-missing --cov-report html --cov-fail-under=70
================================================ test session starts =================================================
platform linux -- Python 3.8.0, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /home/clott/git/xapp-frame-py
plugins: cov-2.8.1
collected 5 items                                                                                                    

tests/test_init.py ...                                                                                         [ 60%]
tests/test_sdl.py .                                                                                            [ 80%]
tests/test_xapps.py F                                                                                          [100%]

====================================================== FAILURES ======================================================
_____________________________________________________ test_flow ______________________________________________________

    def test_flow():
    
        # test variables
        def_pay = None
        sixty_pay = None
    
        # create rmr app
        global rmr_xapp
    
        def post_init(self):
            self.logger.info("suppp info")
            self.logger.debug("suppp debug")
    
        def default_handler(self, summary, sbuf):
            nonlocal def_pay
            def_pay = json.loads(summary["payload"])
            self.rmr_free(sbuf)
    
        rmr_xapp = RMRXapp(default_handler, post_init=post_init, rmr_port=4564, rmr_wait_for_ready=False, use_fake_sdl=True)
    
        def sixtythou_handler(self, summary, sbuf):
            nonlocal sixty_pay
            sixty_pay = json.loads(summary["payload"])
            self.rmr_free(sbuf)
    
        rmr_xapp.register_callback(sixtythou_handler, 60000)
        rmr_xapp.run(thread=True)  # in unit tests we need to thread here or else execution is not returned!
    
        time.sleep(3)
    
        # create a general xapp that will demonstrate some SDL functionality and launch some requests against the rmr xapp
    
        def entry(self):
    
            self.sdl_set("testns", "mykey", 6)
            assert self.sdl_get("testns", "mykey") == 6
            assert self.sdl_find_and_get("testns", "myk") == {"mykey": 6}
            assert self.healthcheck()
    
            val = json.dumps({"test send 60000": 1}).encode()
            self.rmr_send(val, 60000)
    
            val = json.dumps({"test send 60001": 2}).encode()
            self.rmr_send(val, 60001)
    
            # test default healthcheck handler
            self.rmr_send(b"", RIC_HEALTH_CHECK_REQ)
    
            # make sure we got a healthcheck response and that it's good
            time.sleep(2)
            all_msgs = list(self.rmr_get_messages())  # list blows through python generators; should only be 1 here though
            assert len(all_msgs) == 1
            summary, sbuf = all_msgs[0]
            self.rmr_free(sbuf)
            assert summary["payload"] == b"OK\n"
    
        global gen_xapp
        gen_xapp = Xapp(entrypoint=entry, rmr_wait_for_ready=False, use_fake_sdl=True)
>       gen_xapp.run()

tests/test_xapps.py:84: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ricxappframe/xapp_frame.py:380: in run
    self._entrypoint(self)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <ricxappframe.xapp_frame.Xapp object at 0x7f8322729a90>

    def entry(self):
    
        self.sdl_set("testns", "mykey", 6)
        assert self.sdl_get("testns", "mykey") == 6
        assert self.sdl_find_and_get("testns", "myk") == {"mykey": 6}
        assert self.healthcheck()
    
        val = json.dumps({"test send 60000": 1}).encode()
        self.rmr_send(val, 60000)
    
        val = json.dumps({"test send 60001": 2}).encode()
        self.rmr_send(val, 60001)
    
        # test default healthcheck handler
        self.rmr_send(b"", RIC_HEALTH_CHECK_REQ)
    
        # make sure we got a healthcheck response and that it's good
        time.sleep(2)
        all_msgs = list(self.rmr_get_messages())  # list blows through python generators; should only be 1 here though
>       assert len(all_msgs) == 1
E       assert 0 == 1
E        +  where 0 = len([])

tests/test_xapps.py:77: AssertionError
------------------------------------------------ Captured stdout call ------------------------------------------------
{"ts": 1585856565084, "crit": "DEBUG", "id": "ricxappframe.xapp_rmr", "mdc": {}, "msg": "Starting loop thread"}
{"ts": 1585856565085, "crit": "INFO", "id": "ricxappframe.xapp_frame", "mdc": {}, "msg": "suppp info"}
{"ts": 1585856565085, "crit": "DEBUG", "id": "ricxappframe.xapp_frame", "mdc": {}, "msg": "suppp debug"}
{"ts": 1585856565085, "crit": "DEBUG", "id": "ricxappframe.xapp_rmr", "mdc": {}, "msg": "Work loop starting"}
{"ts": 1585856568115, "crit": "DEBUG", "id": "ricxappframe.xapp_rmr", "mdc": {}, "msg": "Starting loop thread"}
{"ts": 1585856568132, "crit": "DEBUG", "id": "ricxappframe.xapp_rmr", "mdc": {}, "msg": "Work loop starting"}
------------------------------------------------ Captured stderr call ------------------------------------------------
1585856569 25250/RMR [INFO] sends: ts=1585856569 src=127.0.0.1:4562 target=127.0.0.1:4564 open=1 succ=3 fail=0 (hard=0 soft=0)
---------------------------------------------- Captured stdout teardown ----------------------------------------------
{"ts": 1585856570257, "crit": "DEBUG", "id": "ricxappframe.xapp_rmr", "mdc": {}, "msg": "Stopping rmr thread. Waiting for last iteration to finish.."}
{"ts": 1585856570282, "crit": "DEBUG", "id": "ricxappframe.xapp_rmr", "mdc": {}, "msg": "Closing rmr connection"}
{"ts": 1585856570282, "crit": "DEBUG", "id": "ricxappframe.xapp_rmr", "mdc": {}, "msg": "Stopping rmr thread. Waiting for last iteration to finish.."}
{"ts": 1585856570319, "crit": "DEBUG", "id": "ricxappframe.xapp_rmr", "mdc": {}, "msg": "Closing rmr connection"}
{"ts": 1585856570319, "crit": "DEBUG", "id": "ricxappframe.xapp_frame", "mdc": {}, "msg": "Stopping queue reading thread.."}

----------- coverage: platform linux, python 3.8.0-final-0 -----------
Name                         Stmts   Miss  Cover   Missing
----------------------------------------------------------
ricxappframe/__init__.py         0      0   100%
ricxappframe/xapp_frame.py      85      8    91%   82-83, 111-112, 142-143, 232, 346
ricxappframe/xapp_rmr.py        37      3    92%   64-66
ricxappframe/xapp_sdl.py        27      4    85%   50, 73, 97, 126
----------------------------------------------------------
TOTAL                          149     15    90%
Coverage HTML written to dir htmlcov
Coverage XML written to file coverage.xml

Required test coverage of 70% reached. Total coverage: 89.93%
============================================== short test summary info ===============================================
FAILED tests/test_xapps.py::test_flow - assert 0 == 1
============================================ 1 failed, 4 passed in 7.47s =============================================
ERROR: InvocationError: '/home/clott/git/xapp-frame-py/.tox/code/bin/pytest --cov ricxappframe --cov-report xml --cov-report term-missing --cov-report html --cov-fail-under=70'
______________________________________________________ summary _______________________________________________________
ERROR:   code: commands failed

Patch-set: 9
Reviewer: Gerrit User 1000014 <1000014@84e4e190-e623-4c37-9eda-58b1937c1b53>