Update patch set 9
Patch Set 9:

The function exists solely for that typecheck.  Without the function and typecheck, the doc generation process fails with the following Exception.  Easily reproduced on a machine WITHOUT THE SHARED OBJECT.  

Exception occurred:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/inspect.py", line 524, in unwrap
    raise ValueError('wrapper loop when unwrapping {!r}'.format(f))
ValueError: wrapper loop when unwrapping ricxappframe.rmr.rmrclib.rmrclib.get_constants.get
The full traceback has been saved in /var/folders/2_/h72sys1530qcp756vs0l4phm0000gn/T/sphinx-err-1efjvrh7.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
ERROR: InvocationError for command /Users/clott/git/o-ran-sc/ric-plt-xapp-frame-py/.tox/docs/bin/sphinx-build -W -b html -n -d /Users/clott/git/o-ran-sc/ric-plt-xapp-frame-py/.tox/docs/tmp/doctrees ./docs/ docs/_build/html (exited with code 2)

Patch-set: 9